"""Pydantic schemas for structured LLM output in the KG extraction pipeline."""

from multi_agent_kg.schemas.extraction_schemas import (
    ExtractedEntity,
    EntityExtractionResponse,
    TypedEntity,
    TypeAssignmentResponse,
    CoreferenceGroup,
    CoreferenceResponse,
    DiscoveredRelation,
    RelationIdentificationResponse,
    ExtractedTriple,
    TripleExtractionResponse,
    LinkedTriple,
    EvidenceLinkingResponse,
    VerifiedTriple,
    VerificationResponse,
    ValidationIssue,
    ValidationResponse,
    DomainAnalysisResponse,
    EntityTypeSpec,
    RelationTypeSpec,
    CriticIssue,
    CriticFeedback,
    CorrectedItem,
    CorrectorResponse,
    EntityResolutionPair,
    EntityResolutionResponse,
)

__all__ = [
    "ExtractedEntity",
    "EntityExtractionResponse",
    "TypedEntity",
    "TypeAssignmentResponse",
    "CoreferenceGroup",
    "CoreferenceResponse",
    "DiscoveredRelation",
    "RelationIdentificationResponse",
    "ExtractedTriple",
    "TripleExtractionResponse",
    "LinkedTriple",
    "EvidenceLinkingResponse",
    "VerifiedTriple",
    "VerificationResponse",
    "ValidationIssue",
    "ValidationResponse",
    "DomainAnalysisResponse",
    "EntityTypeSpec",
    "RelationTypeSpec",
    "CriticIssue",
    "CriticFeedback",
    "CorrectedItem",
    "CorrectorResponse",
    "EntityResolutionPair",
    "EntityResolutionResponse",
]
